### ISSUE TITLE
uninitialized constant Octopress::Tags::Quote (NameError)

### ISSUE THREAD

**Issue by tohuw** [octopress/pullquote-tag#3]
```
$ jekyll build --trace
/Users/tohuw/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/octopress-pullquote-tag-1.0.0/lib/octopress-pullquote-tag.rb:47:in `<top (required)>': uninitialized constant Octopress::Tags::Quote (NameError)
    from /Users/tohuw/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.7.13/lib/bundler/runtime.rb:76:in `require'
    from /Users/tohuw/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.7.13/lib/bundler/runtime.rb:76:in `block (2 levels) in require'
    from /Users/tohuw/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.7.13/lib/bundler/runtime.rb:72:in `each'
    from /Users/tohuw/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.7.13/lib/bundler/runtime.rb:72:in `block in require'
    from /Users/tohuw/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.7.13/lib/bundler/runtime.rb:61:in `each'
    from /Users/tohuw/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.7.13/lib/bundler/runtime.rb:61:in `require'
    from /Users/tohuw/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.7.13/lib/bundler.rb:134:in `require'
    from /Users/tohuw/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/jekyll-2.5.3/lib/jekyll/plugin_manager.rb:38:in `require_from_bundler'
    from /Users/tohuw/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/jekyll-2.5.3/bin/jekyll:16:in `<top (required)>'
    from /Users/tohuw/.rbenv/versions/2.2.0/bin/jekyll:23:in `load'
    from /Users/tohuw/.rbenv/versions/2.2.0/bin/jekyll:23:in `<main>'
```

[Gemfile](https://github.com/tohuw/tohuw.net/blob/b559136b28b8081dc67069800722dce624a8c155/Gemfile)

**Invocation (on about.md):**

```
{% pullquote %}
When writing long-form posts, I find it helpful to include pull-quotes, which help
those scanning a post discern whether or not a post is helpful. It is important to 
note, {" pull-quotes are merely visual in presentation and should not appear twice in the text. "} That 
is why it is preferred to use a CSS only technique for styling pull-quotes.
{% endpullquote %}
```

**Comment by imathis** [comment]
Thanks for the report. This should be fixed in the latest version 1.0.1.
